### ISSUE TITLE
NPM Installation

### ISSUE THREAD

**Issue by bgsa** [brendan-duncan/webgpu_recorder#2]
Is it possible to distribute the project over NPM ? It is easier for installation and dependency manager in JS projects.
Thank you in advance.

**Comment by brendan-duncan** [comment]
I'm very late to getting to this (over a year!), sorry. This script is on NPM, package name 'webgpu_recorder', info in the README.

Also, it's been integrated into my new tool, https://github.com/brendan-duncan/webgpu_inspector.
