### ISSUE TITLE
Allow use with offscreen canvas

### ISSUE THREAD

**Issue by rconde01** [brendan-duncan/webgpu_recorder#7]
Would be nice if I could use this tool with an offscreen canvas.

**Comment by brendan-duncan** [comment]
Sure, I'll look into is when I get the chance.

**Comment by brendan-duncan** [comment]
I did some tweaking of the script to support recording from a web worker with an offscreen canvas. 
I added some info in the README, and a test example:
[worker.html](https://github.com/brendan-duncan/webgpu_recorder/blob/main/test/worker.html)
[worker.js](https://github.com/brendan-duncan/webgpu_recorder/blob/main/test/worker.js)
