### ISSUE TITLE
[BUG] requestAnimationFrame assert because of the returning Promise

### ISSUE THREAD

**Issue by jsyishan** [brendan-duncan/webgpu_recorder#8]
Hi, I'm using[wgpu](https://github.com/gfx-rs/wgpu) and compile it into wasm32-unknown-unknown target, and I got the generated glue js file that includes these following code
```JavaScript
    imports.wbg.__wbg_requestAnimationFrame_549258cfa66011f0 = function() { return handleError(function (arg0, arg1) {
        const ret = getObject(arg0).requestAnimationFrame(getObject(arg1));
        _assertNum(ret);
        return ret;
    }, arguments) };
```

If I click the Start button of the WebGPU Inspector, the window.requestAnimationFrame function has been hook as follow: 
```JavaScript
                window.requestAnimationFrame = async e=>{
                    o((function(r) {
                        if (!t._currentFrameTime) {
                            t._currentFrameTime = r,
                            t._frameStart(r);
                            const s = e(r);
                            s instanceof Promise ? s.then((()=>{
                                t._frameEnd(r),
                                t._currentFrameTime = 0
                            }
                            )) : (t._frameEnd(r),
                            t._currentFrameTime = 0)
                        }
                    }
                    ))
                }
```

while the glue js assumes that the return value of requestAnimationFrame should be a number, and it'll throw the js exception and stop me moving on.

**Comment by brendan-duncan** [comment]
This would be a https://github.com/brendan-duncan/webgpu_inspector issue, but webgpu_recorder would need to be fixed too, so I'll do them both here. I'll have the wrapped requestAnimationFrame return whatever the callback is returning.

**Comment by jsyishan** [comment]
> This would be a https://github.com/brendan-duncan/webgpu_inspector issue, but webgpu_recorder would need to be fixed too, so I'll do them both here. I'll have the wrapped requestAnimationFrame return whatever the callback is returning.

Awesome! Sorry for misreading the repo name lol

**Comment by brendan-duncan** [comment]
Fixed in webgpu_inspector git and the recorder. I'll submit a chrome store version update.

**Comment by jsyishan** [comment]
> Fixed in webgpu_inspector git and the recorder. I'll submit a chrome store version update.

it works fine now :)
